FROM php:7.4-fpm

# Arguments defined in docker-compose.yml
ARG user
ARG uid

RUN apt-get update && apt-get install -y \
    git \
    curl \
    libpng-dev \
    libonig-dev \
    libxml2-dev \
    tzdata \
    libzip-dev \
    zip \
    libpq-dev \
    unzip
    
# Install Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Get latest Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

RUN docker-php-ext-install pdo pdo_mysql mbstring exif pcntl bcmath gd zip

ENV TZ America/Argentina/Buenos_Aires

COPY start.sh /usr/local/bin/start

# Create system user to run Composer and Artisan Commands
RUN useradd -G www-data,root -u $uid -d /home/$user $user

RUN mkdir -p /home/$user/.composer && \
    chown -R $user:$user /home/$user

#subdomain for main or develop
RUN mkdir /var/www/<subdomain>
RUN chown -R www-data:www-data /var/www/<subdomain>
WORKDIR /var/www/<subdomain>

USER $user

#9001 or 9002
EXPOSE <port> 

#CMD ["/usr/local/bin/start"]
